### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by jamesjer** [msoos/cnf-utils#3]
Can you please clarify the licenses of the binary objects produced from this repo?  This is what I've been able to determine.

- GPL v2 only: findmaxvar.py, generate-hard-wffs.sh, xortester.py, xor_to_cnf.py, xor_to_cnf_class.py, xor_to_cnf_test.py
- GPL v3 or later: cnf-fuzz-biere, cnf-fuzz-brummayer.py, sgen4
- MIT: makewff, spacer_test.py
- Public Domain: cnf_model_tester.py

That leaves the following.  What licenses cover them?

- cnf-fuzz-xor.py
- compare.pl
- dbsorter.py
- dimacs-corrector.py
- gen_matrix_based_cnf.py
- largefuzzer
  - MersenneTwister.h is BSD
  - solvertypes.h is MIT
  - largefuzzer.cpp is unknown
- multipart.py

**Comment by msoos** [comment]
Wow, great catch! I have now tried to address all your concerns. Can you please check?

Thanks,

Mate
