### ISSUE TITLE
Arjun with Solution Extender works

### ISSUE THREAD

**Issue by a1880** [msoos/cnf-utils#4]
Hi Mate,

Using your recipe, I could rebuild Cryptominisat and Arjun.
I tested sucessfully with two examples.

The following Boost package should be mentioned in the installation notes:

```
sudo apt-get install libboost-serialization-dev
```

Solextend needs extra care in the installation routine:

```
make solextend
sudo cp solextend /usr/local/bin
```

Internally, `solextend `is still named `arjun-extend`

Greetings,

Axel

**Comment by msoos** [comment]
Ah, thanks! I fixed all these issues now in Arjun, CryptoMiniSat, ApproxMC, and UniGen! I also renamed it to `solextend` in the internal doc :) Thanks again!

**Comment by msoos** [comment]
Oh, related to `solextend` not being installed. I am not yet installing it, I am not confident what I will do with it. It's very experimental for the moment. Maybe it should be called `arjun-extend` or something, but that clashes with `arjun`. I'll think about it. In the meantime it's not installed. It's too experimental I think?
